//
// MenuItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct MenuItem: Codable {


    public var _id: String?

    public var rev: String?

    public var name: String

    public var price: Float

    public var imageUrl: String
    public init(_id: String?, rev: String?, name: String, price: Float, imageUrl: String) { 
        self._id = _id
        self.rev = rev
        self.name = name
        self.price = price
        self.imageUrl = imageUrl
    }
    public enum CodingKeys: String, CodingKey { 
        case _id
        case rev = "_rev"
        case name
        case price
        case imageUrl
    }

}
